"""Research-only QLoRA finetune of Gemma-3-27B on synthetic brain-narration data.

Follow-on run after scripts/finetune_gemma3_smoke.py validates the pipeline. This
one trains on prompts generated by scripts/gen_synth_narrations.py — TRIBE-style
ROI-mean prompts paired with Gemma-26B narrations.

Strictly research-only — output flows into the research finetune track, never
into the commercial bot. See docs/LOCAL_FINETUNE_PLAN.md.

Usage:
    C:/Users/soumi/TRIBEV2/.venv/Scripts/python.exe scripts/finetune_gemma3_brain.py \
        --dataset D:/research/datasets/brain_narrations_<ts>.jsonl \
        --epochs 3
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

os.environ.setdefault('HF_HOME', 'C:/Users/soumi/.cache/huggingface')
os.environ.setdefault('HF_HUB_OFFLINE', '1')
os.environ.setdefault('TRANSFORMERS_OFFLINE', '1')

import unsloth  # must import first
from unsloth import FastLanguageModel, is_bfloat16_supported
import torch

# Py3.14 + dill 0.4.0 incompatibility: pickle.Pickler._batch_setitems signature
# changed in 3.14; dill still calls it with the old 3-arg form. Bypass the
# hasher entirely — fingerprints are only used as cache keys, and we're not
# caching these one-shot datasets anyway.
import hashlib
import datasets.fingerprint as _fp


def _stable_hash(value) -> str:
    return hashlib.sha256(repr(value).encode('utf-8', errors='replace')).hexdigest()


_fp.Hasher.hash = classmethod(lambda cls, value: _stable_hash(value))
_fp.generate_fingerprint = lambda dataset: _stable_hash(id(dataset))

from datasets import load_dataset
from trl import SFTTrainer, SFTConfig


BASE_MODEL      = 'C:/Users/soumi/.cache/huggingface/hub/models--unsloth--gemma-3-27b-it-bnb-4bit/snapshots/c08b2ba63738aa8cfc60f06741d6356ef4e60b3f'
MAX_SEQ_LENGTH  = 2048
LORA_R          = 16
LORA_ALPHA      = 32
BATCH_SIZE      = 1
GRAD_ACCUM      = 8
LR              = 1.5e-4
WARMUP          = 30
LOG_EVERY       = 5
SAVE_EVERY      = 200


_SYSTEM = (
    "You are a neuroscience narration assistant. Given a stimulus description, duration, "
    "peak-activity time, and top Schaefer-400 cortical regions by mean |z|, explain what "
    "the brain is doing in 3-5 sentences. Group regions into Yeo-7 networks (Vis, SomMot, "
    "DorsAttn, SalVentAttn, Limbic, Cont, Default). Be factual, compact, and avoid "
    "diagnostic claims."
)

_TEMPLATE = """<start_of_turn>user
{system}

{prompt}<end_of_turn>
<start_of_turn>model
{completion}<end_of_turn>"""


def _load_jsonl(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open('r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def _write_text_jsonl(rows: list[dict], system: str, template: str, eos: str, out_path: Path) -> None:
    with out_path.open('w', encoding='utf-8') as f:
        for r in rows:
            text = template.format(system=system, prompt=r['prompt'], completion=r['completion']) + eos
            f.write(json.dumps({'text': text}, ensure_ascii=False) + '\n')


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--dataset', type=str, required=True)
    ap.add_argument('--epochs', type=int, default=3)
    ap.add_argument('--seed', type=int, default=3407)
    ap.add_argument('--lora-r', type=int, default=LORA_R)
    ap.add_argument('--lora-alpha', type=int, default=LORA_ALPHA)
    ap.add_argument('--tag', type=str, default='')
    args = ap.parse_args()

    data_path = Path(args.dataset)
    if not data_path.exists():
        raise SystemExit(f'dataset not found: {data_path}')

    ts = int(time.time())
    suffix = f'-{args.tag}' if args.tag else ''
    out_dir = Path(f'D:/research/weights/gemma3-27b-brain{suffix}-{ts}')
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f'[brain-ft] out     = {out_dir}')
    print(f'[brain-ft] base    = {BASE_MODEL}')
    print(f'[brain-ft] data    = {data_path}')
    print(f'[brain-ft] epochs  = {args.epochs}')
    print(f'[brain-ft] lora_r  = {args.lora_r}, lora_alpha = {args.lora_alpha}')
    print(f'[brain-ft] torch   = {torch.__version__}  cuda_cap = {torch.cuda.get_device_capability(0)}')
    print(f'[brain-ft] bf16    = {is_bfloat16_supported()}')

    rows = _load_jsonl(data_path)
    print(f'[brain-ft] loaded {len(rows)} rows')

    t0 = time.time()
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name     = BASE_MODEL,
        max_seq_length = MAX_SEQ_LENGTH,
        dtype          = None,
        load_in_4bit   = True,
    )
    print(f'[brain-ft] model loaded in {time.time()-t0:.1f}s')

    model = FastLanguageModel.get_peft_model(
        model,
        r               = args.lora_r,
        target_modules  = [
            'q_proj', 'k_proj', 'v_proj', 'o_proj',
            'gate_proj', 'up_proj', 'down_proj',
        ],
        lora_alpha      = args.lora_alpha,
        lora_dropout    = 0.0,
        bias            = 'none',
        use_gradient_checkpointing = 'unsloth',
        random_state    = args.seed,
        use_rslora      = False,
        loftq_config    = None,
    )

    EOS = tokenizer.eos_token

    # Pre-format to a text-only JSONL on disk; load via HF datasets' JSON loader
    # to sidestep Python 3.14 + dill pickle incompatibility in Dataset.from_list.
    text_path = out_dir / 'train_text.jsonl'
    _write_text_jsonl(rows, _SYSTEM, _TEMPLATE, EOS, text_path)
    ds = load_dataset('json', data_files=str(text_path), split='train')
    print(f'[brain-ft] dataset formatted: {ds.column_names} ({len(ds)} rows) at {text_path}')

    total_steps_per_epoch = max(1, len(ds) // (BATCH_SIZE * GRAD_ACCUM))
    total_steps = total_steps_per_epoch * args.epochs
    print(f'[brain-ft] target total_steps ~= {total_steps}')

    cfg = SFTConfig(
        per_device_train_batch_size = BATCH_SIZE,
        gradient_accumulation_steps = GRAD_ACCUM,
        warmup_steps    = WARMUP,
        num_train_epochs = args.epochs,
        learning_rate   = LR,
        logging_steps   = LOG_EVERY,
        save_steps      = SAVE_EVERY,
        optim           = 'adamw_8bit',
        weight_decay    = 0.01,
        lr_scheduler_type = 'cosine',
        seed            = args.seed,
        output_dir      = str(out_dir),
        save_total_limit = 3,
        report_to       = 'none',
        bf16            = is_bfloat16_supported(),
        fp16            = not is_bfloat16_supported(),
        dataset_text_field = 'text',
        max_length      = MAX_SEQ_LENGTH,
        packing         = False,
        dataset_num_proc = 2,
    )

    trainer = SFTTrainer(
        model           = model,
        processing_class = tokenizer,
        train_dataset   = ds,
        args            = cfg,
    )

    print(f'[brain-ft] trainer ready; VRAM used = {torch.cuda.memory_allocated()/1e9:.2f} GB')

    t_start = time.time()
    stats = trainer.train()
    elapsed = time.time() - t_start

    print(f'\n[brain-ft] DONE in {elapsed/60:.1f} min')
    print(f'[brain-ft] train_loss = {stats.training_loss:.4f}')
    print(f'[brain-ft] peak VRAM  = {torch.cuda.max_memory_allocated()/1e9:.2f} GB')

    trainer.save_model(str(out_dir / 'final'))
    tokenizer.save_pretrained(str(out_dir / 'final'))
    print(f'[brain-ft] adapter saved -> {out_dir / "final"}')


if __name__ == '__main__':
    main()
